export const FieldsLength = {
  STORAGE_NAME: 20,
  STORAGE_ADDRESS: 40,

  INVOICE_NUMBER: 20,

  PRODUCT_OWNER_NAME: 30,
  PRODUCT_OWNER_ADDRESS: 40,

  CLIENT_NAME: 30,

  USER_NAME: 20,
  USER_SURNAME: 20,
  USER_PATRONYMIC: 20,
  USER_EMAIL: 50,
  USER_TOWN: 20,
  USER_STREET: 20,
  USER_HOUSE: 5,
  USER_FLAT: 5,
  USER_MAX_LOGIN: 15,
  USER_MIN_LOGIN: 5,
  USER_MAX_PASSWORD: 20,
  USER_MIN_PASSWORD: 5,

  CAR_NUMBER: 10,

  PRODUCT_NAME: 50,

  CHECKPOINT_ADDRESS: 50,

  ARRIVAL_TIME: 5,

  EMAIL_SUBJECT: 50,
  EMAIL_TEXT: 300,
  TEMPLATE_MAX_LENGTH: 350
};
